// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: cite/cite.proto

package cite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type POWRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pow string `protobuf:"bytes,1,opt,name=pow,proto3" json:"pow,omitempty"`
}

func (x *POWRequest) Reset() {
	*x = POWRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cite_cite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POWRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POWRequest) ProtoMessage() {}

func (x *POWRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cite_cite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POWRequest.ProtoReflect.Descriptor instead.
func (*POWRequest) Descriptor() ([]byte, []int) {
	return file_cite_cite_proto_rawDescGZIP(), []int{0}
}

func (x *POWRequest) GetPow() string {
	if x != nil {
		return x.Pow
	}
	return ""
}

type CiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cite      string `protobuf:"bytes,1,opt,name=cite,proto3" json:"cite,omitempty"`
	PowRiddle string `protobuf:"bytes,2,opt,name=powRiddle,proto3" json:"powRiddle,omitempty"`
}

func (x *CiteResponse) Reset() {
	*x = CiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cite_cite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiteResponse) ProtoMessage() {}

func (x *CiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cite_cite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiteResponse.ProtoReflect.Descriptor instead.
func (*CiteResponse) Descriptor() ([]byte, []int) {
	return file_cite_cite_proto_rawDescGZIP(), []int{1}
}

func (x *CiteResponse) GetCite() string {
	if x != nil {
		return x.Cite
	}
	return ""
}

func (x *CiteResponse) GetPowRiddle() string {
	if x != nil {
		return x.PowRiddle
	}
	return ""
}

var File_cite_cite_proto protoreflect.FileDescriptor

var file_cite_cite_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x69, 0x74, 0x65, 0x2f, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x69, 0x74, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x50, 0x4f, 0x57, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x6f, 0x77, 0x22, 0x40, 0x0a, 0x0c, 0x43, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x6f, 0x77, 0x52, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x6f, 0x77, 0x52, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x32, 0x44, 0x0a, 0x0b, 0x43, 0x69, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43,
	0x69, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x50, 0x4f, 0x57, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x43, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x13, 0x5a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cite_cite_proto_rawDescOnce sync.Once
	file_cite_cite_proto_rawDescData = file_cite_cite_proto_rawDesc
)

func file_cite_cite_proto_rawDescGZIP() []byte {
	file_cite_cite_proto_rawDescOnce.Do(func() {
		file_cite_cite_proto_rawDescData = protoimpl.X.CompressGZIP(file_cite_cite_proto_rawDescData)
	})
	return file_cite_cite_proto_rawDescData
}

var file_cite_cite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cite_cite_proto_goTypes = []interface{}{
	(*POWRequest)(nil),   // 0: cite.POWRequest
	(*CiteResponse)(nil), // 1: cite.CiteResponse
}
var file_cite_cite_proto_depIdxs = []int32{
	0, // 0: cite.CiteService.GetCite:input_type -> cite.POWRequest
	1, // 1: cite.CiteService.GetCite:output_type -> cite.CiteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cite_cite_proto_init() }
func file_cite_cite_proto_init() {
	if File_cite_cite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cite_cite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POWRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cite_cite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cite_cite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cite_cite_proto_goTypes,
		DependencyIndexes: file_cite_cite_proto_depIdxs,
		MessageInfos:      file_cite_cite_proto_msgTypes,
	}.Build()
	File_cite_cite_proto = out.File
	file_cite_cite_proto_rawDesc = nil
	file_cite_cite_proto_goTypes = nil
	file_cite_cite_proto_depIdxs = nil
}
